version: '3.9 '

services:
  django:
    image: cron_shedule_using_docker
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/django
    container_name: my_container_cron_sheduler
    command: python3 manage.py runserver 0.0.0.0:8000